sudo: required
services:
  - docker

#addons:
#  apt:
#    packages:
#      - docker-ce

before_install:
  - docker --version
  - docker build -t iamritraj/docker-react -f Dockerfile.dev .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push iamritraj/docker-react:1

script:
  - docker run iamritraj/docker-react npm run test -- --coverage

# deploy:
  # provider: elasticbeanstalk
  # region: "us-west-2"
  # app: "docker"
  # env: "Docker-env"
  # bucket_name: "elasticbeanstalk-us-west-2-306476627547"
  # bucket_path: "docker"
  # on:
    # branch: master
  # access_key_id: $AWS_ACCESS_KEY
  # secret_access_key:
    # secure: "$AWS_SECRET_KEY"

